<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $fillable=[
      'title', 'body', 'user_id', 'photo_id', 'category_id', 'is_active',
    ];

    public function photo(){
        return $this->belongsTo('App\Photo');
    }


    public function user(){
        return $this->belongsTo('App\User');
    }
    public function category(){
        return $this->belongsTo('App\Category');
    }

    // polymorphic m2m with photo
    public function photos(){
        return $this->morphMany('App\Photo', 'photoable');
    }
    public function delete()
    {
        unlink(public_path().$this->photos()->first()->path);
        $this->photos()->first()->delete();


        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
